export const highlighter = {
  YelloColor1: '#FFFEBD',
  GreenColor1: '#F6FDD7',
  redColor1: '#F9D9CC',
  blueColor1: '#CFE4FF',
  purpleColor1: '#E6E6FF',
  brownColor1: '#E3D0C1',
  YelloColor2: '#FFFC70',
  GreenColor2: '#E8FD8B',
  redColor2: '#FDC3C4',
  blueColor2: '#B5D6FF',
  purpleColor2: '#CECCFF',
  brownColor2: '#D6C4C1',
  YelloColor3: '#FCF8CE',
  GreenColor3: '#DEF76F',
  redColor3: '#FFD3CF',
  blueColor3: '#D6F0FF',
  purpleColor3: '#B6B3FF',
  brownColor3: '#CCBEB8',
  YelloColor4: '#FBEC96',
  GreenColor4: '#EAF7D6',
  redColor4: '#FFA3A7',
  blueColor4: '#A3DDFF',
  purpleColor4: '#E2D6FF',
  brownColor4: '#BFBFBF',
};
